server:
  port: 8085 # 指定启动端口

logging:
  file:
    path: ./logs

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

mq-consumer: # MQ 消费者
  follow-unfollow: # 关注、取关
    rate-limit: 5000 # 每秒限流阈值