server:
  port: 8087 # 指定启动端口

logging:
  file:
    path: ./logs

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml