server:
  port: 8080 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

ali:
  sms:
    endpoint: dysmsapi.aliyuncs.com
    sign-name: "阿里云短信测试"
    template-code: "SMS_154950909"